export const pages: PageMetadata[] = [
    {
        title: "AnimeFX - Various Works",
        desc: "Various design work for the AnimeFX club.",
        tags: ["Graphic Design", "2023"],
        link: "/animefx",
        thumb: {src: "/AnimeFX/thumb.png", alt: "AnimeFX"},
    },
    {
        title: "CoSE - Various Works",
        desc: "Various design work for the College of Science & Engineering at SFSU.",
        tags: ["Graphic Design", "2023"],
        link: "/cose",
        thumb: {src: "/CoSE/thumb.png", alt: "CoSE"},
    },
    {
        title: "Gorilla",
        desc: "Photo tagging app using AI image recognition.",
        tags: ["UI/UX", "2022"],
        link: "/gorilla",
        thumb: {src: "/Gorilla/thumb.png", alt: "Gorilla"},
    },
    {
        title: "Leaplist",
        desc: "Gamified homework/task management app.",
        tags: ["UI/UX", "2022"],
        link: "/leaplist",
        thumb: {src: "/Leaplist/thumb.png", alt: "Leaplist"},
    },
    {
        title: "LiveTL",
        desc: "Livestream chat translation for YouTube and Twitch",
        tags: ["UI/UX", "2022"],
        link: "/livetl",
        thumb: {src: "/LiveTL/LiveTL Thumb.png", alt: "LiveTL"},
    },
    {
        title: "Redux Signage",
        desc: "Store aisle signage for a hypothetical electronics store",
        tags: ["Graphic Design", "2022"],
        link: "/redux-signage",
        thumb: {src: "/Redux/thumb.png", alt: "Redux"},
    },
    {
        title: "Vaso Azzurro Rebrand",
        desc: "Rebranding and logo design for small business",
        tags: ["Graphic Design", "2022"],
        link: "/vaso-azzurro-rebrand",
        thumb: {src: "/VasoAzzurro/thumb.png", alt: "Rebrand"},
    },
    {
        title: "Design Now! - Paul Rand",
        desc: "Fictitious magazine issue on the graphic designer Paul Rand",
        tags: ["Graphic Design", "2021"],
        link: "/design-now-paul-rand",
        thumb: {src: "/DesignNowPaulRand/thumb.png", alt: "Paul Rand"},
    },
    {
        title: "Tree",
        desc: "Illustration/digital artwork",
        tags: ["Graphic Design", "2021"],
        link: "/tree",
        thumb: {src: "/Tree/thumb.png", alt: "Tree"},
    },
    {
        title: "Pogify",
        desc: "Music streaming service for Twitch streams",
        tags: ["UI/UX", "2020"],
        link: "/pogify",
        thumb: {src: "/Pogify/thumb.png", alt: "Pogify"},
    },
]