export const pages: PageMetadata[] = [
    {
        title: "Piqued",
        desc: "Social blogging platform",
        tags: ["Web Development", "JS", "Svelte", "UI/UX", "2023"],
        link: "/piqued",
        thumb: {src: "/Piqued/Thumb.png", alt: "Piqued"},
    },
    // {
    //     title: "Monopoly",
    //     desc: "Online multiplayer Monopoly game",
    //     tags: ["Web Development", "JS", "React", "UI/UX", "2023"],
    //     link: "/",
    //     thumb: {src: "/burger.jpg", alt: "Burger"},
    // },
    {
        title: "CarrotList",
        desc: "Grocery shopping price tracker app.",
        tags: ["iOS", "Swift", "2023"],
        link: "/carrotlist",
        thumb: {src: "/CarrotList/thumb.jpg", alt: "CarrotList"},
    },
    {
        title: "SNFC Registration",
        desc: "Student registration system for the Sierra Nevada Field Campus of SFSU",
        tags: ["Web Development", "2023"],
        link: "/snfc",
        thumb: {src: "/SNFC/Home.png", alt: "SNFC"},
    },
    {
        title: "StreamModules",
        desc: "Landing page for a hypothetical hardware/software services company.",
        tags: ["Web Development", "2022"],
        link: "/streammodules",
        thumb: {src: "/StreamModules/thumb.png", alt: "StreamModules"},
    },
    {
        title: "Broken Record",
        desc: "Musical Instrument App",
        tags: ["Web Development", "TS", "React", "2022"],
        link: "/broken-record",
        thumb: {src: "/BrokenRecord/thumb.png", alt: "Broken Record"},
    },
    {
        title: "Cosmarauders",
        desc: "Procedurally generated, space-themed rougelike game",
        tags: ["Unity", "C#", "2022"],
        link: "/cosmarauders",
        thumb: {src: "/Cosmarauders/game.png", alt: "Cosmarauders"},
    },
    {
        title: "ATeM",
        desc: "Online payment and cash transfer app.",
        tags: ["Web Development", "JS", "UI/UX", "2021"],
        link: "/atem",
        thumb: {src: "/ATeM/thumb.png", alt: "ATeM"},
    },
    {
        title: "Submarine/Subylert",
        desc: "Subscription tracking app",
        tags: ["Android", "Java", "UI/UX", "2021"],
        link: "/submarine",
        thumb: {src: "/Submarine/thumb.jpg", alt: "Submarine"},
    },
    {
        title: "Imagetree",
        desc: "Image hosting and sharing platform",
        tags: ["Web Development", "JS", "UI/UX", "2020"],
        link: "/imagetree",
        thumb: {src: "/Imagetree/thumb.png", alt: "Imagetree"},
    },
]